# -*- coding: utf-8 -*-
"""news_summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1286yXVq4Co1BpGdOTKRnXbCvWlEb4WG1
"""

import requests
from bs4 import BeautifulSoup
from transformers import pipeline

# Step 1: Get article
url = "https://kalingatv.com/entertainment/industrialist-sunjay-kapurs-funeral-in-new-delhi-today-know-why-his-last-rites-were-delayed/"
headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(url, headers=headers)

# Step 2: Extract text
soup = BeautifulSoup(response.content, 'html.parser')
paragraphs = soup.find_all('p')
text = ' '.join([para.get_text() for para in paragraphs])

# Step 3: Load summarizer with PyTorch only
summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6", framework="pt")

# Step 4: Shorten text if needed
text = text[:1024]

# Step 5: Get summary
summary = summarizer(text, max_length=100, min_length=30, do_sample=False)
print("Summary:\n", summary[0]['summary_text'])

"""
"The 13-year-old boy did a fantastic job making this project by himself. We are proud of him."
"""